### ISSUE TITLE
New findvect

### ISSUE THREAD

**Issue by kranonetka** [RockThisParty/Knapsack#2]
findvect(a,L1/b)
Ob 8⇒j
§1 ∇j ↑(a≥L1j)2 j↪3 →1
§2 a-L1j⇒a 7-j⇒m 1<m⇒m b∨m⇒b j↦1
§3 **

**Comment by ragdked** [comment]
findvect(a,L1/b)
Ob Q3-1⇒i
§1 ↑(a≥L1i) ∇i i↪3 →1
§2 a-L1j⇒a c>1⇒c ∇j b∨c⇒c
§3 **
